# Generated by Django 4.2 on 2025-03-17 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DisasterCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Material icon name', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Disaster Category',
                'verbose_name_plural': 'Disaster Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField()),
                ('content', models.TextField()),
                ('source', models.CharField(blank=True, max_length=255)),
                ('source_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Emergency Resource',
                'verbose_name_plural': 'Emergency Resources',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='DisasterProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='disaster_projects/')),
                ('location', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('planned', 'Planned')], default='active', max_length=20)),
                ('funding_goal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('funds_raised', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='disasters.disastercategory')),
            ],
            options={
                'verbose_name': 'Disaster Project',
                'verbose_name_plural': 'Disaster Projects',
                'ordering': ['-featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisasterDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('donor_name', models.CharField(blank=True, max_length=255)),
                ('donor_email', models.EmailField(blank=True, max_length=254)),
                ('anonymous', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True)),
                ('transaction_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='disasters.disasterproject')),
            ],
            options={
                'verbose_name': 'Disaster Donation',
                'verbose_name_plural': 'Disaster Donations',
                'ordering': ['-created_at'],
            },
        ),
    ]
