# Generated by Django 5.0.6 on 2025-03-19 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift_cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcarddesign',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gift_cards/designs/'),
        ),
    ]
