# Generated by Django 4.2 on 2025-03-28 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='chatsession',
            options={'ordering': ['-updated_at']},
        ),
        migrations.RenameField(
            model_name='chatmessage',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='appchatbotresponse',
            name='follow_up_questions',
        ),
        migrations.AddField(
            model_name='appchatbotresponse',
            name='_follow_up_questions',
            field=models.TextField(blank=True, db_column='follow_up_questions', null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appchatbotresponse',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('account', 'Account Management'), ('donation', 'Donations'), ('project', 'Projects'), ('technical', 'Technical Support'), ('security', 'Security')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='appchatbotresponse',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='appchatbotresponse',
            name='question_pattern',
            field=models.TextField(help_text='Regex pattern to match user questions'),
        ),
        migrations.AlterField(
            model_name='appchatbotresponse',
            name='response',
            field=models.TextField(help_text='Response to provide when pattern matches'),
        ),
        migrations.AlterField(
            model_name='chatfeedback',
            name='rating',
            field=models.IntegerField(choices=[(1, 'Not Helpful'), (2, 'Somewhat Helpful'), (3, 'Helpful'), (4, 'Very Helpful'), (5, 'Excellent')], default=3),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='chatfeedback',
            unique_together={('message', 'user')},
        ),
        migrations.AddIndex(
            model_name='appchatbotresponse',
            index=models.Index(fields=['category', 'is_active'], name='chatbot_app_categor_823815_idx'),
        ),
        migrations.AddIndex(
            model_name='appchatbotresponse',
            index=models.Index(fields=['updated_at'], name='chatbot_app_updated_87f6a8_idx'),
        ),
        migrations.AddIndex(
            model_name='chatfeedback',
            index=models.Index(fields=['message', 'rating'], name='chatbot_cha_message_95c1be_idx'),
        ),
        migrations.AddIndex(
            model_name='chatfeedback',
            index=models.Index(fields=['user'], name='chatbot_cha_user_id_3de7fe_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session', 'created_at'], name='chatbot_cha_session_24e989_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['role'], name='chatbot_cha_role_e49465_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['user'], name='chatbot_cha_user_id_25d1f5_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['session_id'], name='chatbot_cha_session_9384e5_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['created_at'], name='chatbot_cha_created_70ca81_idx'),
        ),
    ]
