# Generated by Django 4.2 on 2025-03-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyPartnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('description', models.TextField()),
                ('partnership_type', models.CharField(choices=[('employee_giving', 'Employee Giving'), ('cause_marketing', 'Cause Marketing'), ('disaster_response', 'Disaster Response'), ('custom', 'Custom Partnership')], max_length=50)),
                ('website', models.URLField(blank=True, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Partnership',
                'verbose_name_plural': 'Company Partnerships',
                'ordering': ['-featured', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PartnershipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('contact_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('partnership_type', models.CharField(choices=[('employee_giving', 'Employee Giving'), ('cause_marketing', 'Cause Marketing'), ('disaster_response', 'Disaster Response'), ('custom', 'Custom Partnership')], max_length=50)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewing', 'Reviewing'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Partnership Application',
                'verbose_name_plural': 'Partnership Applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
