# Generated by Django 5.0.6 on 2025-03-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_address_userprofile_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('donor', 'Donor'), ('volunteer', 'Volunteer')], default='donor', max_length=10),
        ),
    ]
